# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('semestre', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Licenciaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('semestre', models.IntegerField(default=0)),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Licenciaturas')),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('especialidad', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='alumnos',
            name='licenciatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Licenciaturas'),
        ),
    ]
