# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
